import type { ProdutoBusca } from './Busca.types';

/**
 * Mock temporário para testes de layout e fluxo da página de busca.
 */
export const produtosBuscaMock: ProdutoBusca[] = [
    {
        id: 1,
        title: 'Furadeira Parafusadeira Impacto 1/2',
        brand: 'Bosch',
        category: 'Ferramentas Elétricas',
        price: '45,00',
        images: ['src/assets/Furadeira1.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.5,
        reviewCount: 124,
        paymentMethods: ['Cartão de Crédito', 'Pix'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 2,
        title: 'Pistola de Pintura Profissional',
        brand: 'Black & Decker',
        category: 'Ferramentas Elétricas',
        price: '30,00',
        images: ['src/assets/pistolaPintura.png'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.2,
        reviewCount: 87,
        paymentMethods: ['Cartão de Crédito', 'Pix'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 3,
        title: 'Chave de Fenda Hidráulica Manual',
        brand: 'Makita',
        category: 'Ferramentas Manuais',
        price: '15,00',
        images: ['src/assets/Furadeira3.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 3.7,
        reviewCount: 201,
        paymentMethods: ['Pix'],
        available: false,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 4,
        title: 'Aparador De Grama Bipartido',
        brand: 'DeWalt',
        category: 'Equipamentos de Jardinagem',
        price: '85,00',
        images: ['src/assets/aparadorGrama.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.1,
        reviewCount: 45,
        paymentMethods: ['Cartão de Crédito'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 5,
        title: 'Serra Tico-Tico de Bancada',
        brand: 'Bosch',
        category: 'Ferramentas Elétricas',
        price: '50,00',
        images: ['src/assets/parafusadeira-furadeira-WAP.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.4,
        reviewCount: 76,
        paymentMethods: ['Cartão de Crédito', 'Pix'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 6,
        title: 'Kit Chaves Combinadas Premium',
        brand: 'DeWalt',
        category: 'Ferramentas Manuais',
        price: '25,00',
        images: ['src/assets/aparadorGrama.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.6,
        reviewCount: 153,
        paymentMethods: ['Cartão de Crédito', 'Pix'],
        available: false,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 7,
        title: 'Cortador de Grama Dirigível',
        brand: 'Black & Decker',
        category: 'Equipamentos de Jardinagem',
        price: '210,00',
        images: ['src/assets/parafusadeira-wap.png'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 2.9,
        reviewCount: 27,
        paymentMethods: ['Cartão de Crédito'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 8,
        title: 'Parafusadeira Furadeira de Impacto Hanabi',
        brand: 'Makita',
        category: 'Ferramentas Elétricas',
        price: '28,00',
        images: ['src/assets/Furadeira3.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.7,
        reviewCount: 201,
        paymentMethods: ['Pix'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 9,
        title: 'Parafusadeira e Furadeira WAP 12V',
        brand: 'WAP',
        category: 'Ferramentas Elétricas',
        price: '18,00',
        images: ['src/assets/Furadeira4.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.3,
        reviewCount: 62,
        paymentMethods: ['Cartão de Crédito', 'Pix'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
    {
        id: 10,
        title: 'Parafusadeira e Furadeira WAP BPF 12V',
        brand: 'WAP',
        category: 'Ferramentas Elétricas',
        price: '18,00',
        images: ['src/assets/parafusadeira-furadeira-WAP.webp'],
        imageVerificado: 'src/assets/verificadoAzul.png',
        imageNota: 'src/assets/StarFullYellow.png',
        rating: 4.0,
        reviewCount: 38,
        paymentMethods: ['Cartão de Crédito'],
        available: true,
        locador: 'Loja Exemplo',
        localizacao: 'São Paulo - SP',
        estoqueDisponivel: 10,
    },
];