import type { ReservaData } from './MinhasReservas.types';

import furadeiraBosch from '../../../assets/ProdutosImg/FuradeiraBosch.png';
import pistolaPintura from '../../../assets/ProdutosImg/pistolaPintura.png';
import furadeiraBlackTools from '../../../assets/ProdutosImg/FuradeiraTheBlackTools.png';
import aparadorGrama from '../../../assets/ProdutosImg/aparadorGrama.png';
import furadeiraWap from '../../../assets/ProdutosImg/FuradeiraWapPreta.png';
import lixadeiraOrbital from '../../../assets/ProdutosImg/lixadeiraEletrica.png';

// Mock de reservas. Estrutura pensada para mapear diretamente a resposta futura da API.
export const mockReservas: ReservaData[] = [
  {
    id: '1',
    produto: 'Furadeira Bosch GSB 13 RE',
    imagem: furadeiraBosch,
    periodo: '15 Jul – 18 Jul 2025',
    locador: 'Carlos Silva',
    status: 'pendente',
    mensagemStatus: 'Aguardando aprovação do locador',
    categoria: 'Elétrica • Parafusadeira/Furadeira',
    avaliacaoLocador: 4.8,
    numeroAvaliacoes: 120,
    localizacao: 'São Paulo - SP',
    dataInicio: '15/07/2025',
    horaInicio: '09:00',
    dataFim: '18/07/2025',
    horaFim: '18:00',
    quantidade: 1,
    valorEstimado: 'R$ 180,00',
  },
  {
    id: '2',
    produto: 'Pistola Pintura Sucção 1000ml 3 Bicos 1.2 1.5 1.8 BTPT1100 Profissional The Black Tools',
    imagem: pistolaPintura,
    periodo: '10 Jul – 12 Jul 2025',
    locador: 'João Ferreira',
    status: 'aprovada',
    mensagemStatus: 'Reserva aprovada',
    categoria: 'Elétrica • Pintura',
    avaliacaoLocador: 4.6,
    numeroAvaliacoes: 84,
    localizacao: 'Campinas - SP',
    dataInicio: '10/07/2025',
    horaInicio: '08:00',
    dataFim: '12/07/2025',
    horaFim: '17:00',
    quantidade: 1,
    valorEstimado: 'R$ 90,00',
  },
  {
    id: '3',
    produto: 'Furadeira Parafusadeira Sem Fio A Bateria Tb-12e 12v 3/8 10mm Com Maleta E Acessórios The Black Tools',
    imagem: furadeiraBlackTools,
    periodo: '05 Jul – 07 Jul 2025',
    locador: 'Maria Oliveira',
    status: 'recusada',
    mensagemStatus: 'Reserva recusada pelo locador',
    categoria: 'Elétrica • Parafusadeira/Furadeira',
    avaliacaoLocador: 4.9,
    numeroAvaliacoes: 63,
    localizacao: 'São Paulo - SP',
    dataInicio: '05/07/2025',
    horaInicio: '09:00',
    dataFim: '07/07/2025',
    horaFim: '18:00',
    quantidade: 1,
    valorEstimado: 'R$ 70,00',
    motivoRecusa: 'Infelizmente a ferramenta estará em manutenção na data solicitada.',
  },
  {
    id: '4',
    produto: 'Aparador De Grama Bipartido Tramontina Apb1500t Cor Laranja Escuro 220v',
    imagem: aparadorGrama,
    periodo: '01 Jul – 03 Jul 2025',
    locador: 'Ana Souza',
    status: 'cancelada',
    mensagemStatus: 'Reserva cancelada',
    categoria: 'Jardinagem • Aparador de Grama',
    avaliacaoLocador: 4.7,
    numeroAvaliacoes: 41,
    localizacao: 'Guarulhos - SP',
    dataInicio: '01/07/2025',
    horaInicio: '09:00',
    dataFim: '03/07/2025',
    horaFim: '18:00',
    quantidade: 1,
    valorEstimado: 'R$ 60,00',
  },
  {
    id: '5',
    produto: 'Parafusadeira E Furadeira A Bateria Li-ion Wap Wf 12k3.2 Carregador Com Maleta E Kit De 11 Acessórios',
    imagem: furadeiraWap,
    periodo: '20 Jul – 25 Jul 2025',
    locador: 'Ricardo Gomes',
    status: 'pendente',
    mensagemStatus: 'Aguardando aprovação do locador',
    categoria: 'Elétrica • Parafusadeira/Furadeira',
    avaliacaoLocador: 4.5,
    numeroAvaliacoes: 57,
    localizacao: 'Osasco - SP',
    dataInicio: '20/07/2025',
    horaInicio: '09:00',
    dataFim: '25/07/2025',
    horaFim: '18:00',
    quantidade: 1,
    valorEstimado: 'R$ 250,00',
  },
  {
    id: '6',
    produto: 'Lixadeira Orbital Bosch GSS 140',
    imagem: lixadeiraOrbital,
    periodo: '22 Jul – 24 Jul 2025',
    locador: 'Carlos Silva',
    status: 'aprovada',
    mensagemStatus: 'Reserva aprovada',
    categoria: 'Elétrica • Lixadeira',
    avaliacaoLocador: 4.8,
    numeroAvaliacoes: 120,
    localizacao: 'São Paulo - SP',
    dataInicio: '22/07/2025',
    horaInicio: '09:00',
    dataFim: '24/07/2025',
    horaFim: '18:00',
    quantidade: 1,
    valorEstimado: 'R$ 120,00',
  },
];
